[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn mythology_project.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10